

server:
  port: 8081
  error:
    include-message: always
spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: zantaspa2026
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
